cluster.name: "docker-cluster"
network.host: 0.0.0.0
http.cors.enabled: true
http.cors.allow-origin: "*"
xpack.security.enabled: false
xpack.license.self_generated.type: basic
xpack.security.http.ssl.enabled: false
xpack.security.transport.ssl.enabled: false
