version: '3.4'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.2
    container_name: elasticsearch
    environment:
       - discovery.type=single-node
    networks:
      - elk
    volumes:
      - ./elasticsearch/data/:/usr/share/elasticsearch/data/
      - ./elasticsearch/plugins/:/usr/share/elasticsearch/plugins/
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml

  logstash:
    image: docker.elastic.co/logstash/logstash:8.8.2
    container_name: logstash
    privileged: true
    ports:
      - 9527:9527
    networks:
      - elk
    volumes:
      - ./logstash/pipeline/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    depends_on:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:8.8.2
    container_name: kibana
    ports:
      - 5601:5601
    networks:
      - elk
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
    depends_on:
      - elasticsearch

networks:
  elk:
    driver: bridge
