version: '3.4'

services:
  sample_a:
    image: ${DOCKER_REGISTRY-}samplea
    build:
      context: .
      dockerfile: services/sample_a/Dockerfile

  sample_b:
    image: ${DOCKER_REGISTRY-}sampleb
    build:
      context: .
      dockerfile: services/sample_b/Dockerfile

  auth:
    image: ${DOCKER_REGISTRY-}auth
    build:
      context: .
      dockerfile: sso/auth/Dockerfile

