version: '3.4'

services:
  consul-client:
    image: hashicorp/consul
    container_name: consul
    networks:
      - multilevelcacheonk8s
    ports:
      - "8500:8500"
    command: "agent -client=0.0.0.0 -ui -retry-join=consul-server-1 -node=consul-client"

  apigateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - multilevelcacheonk8s
    ports:
      - "5009:80"

  sample-a:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - multilevelcacheonk8s
    depends_on:
      - consul-client

  sample-b:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - multilevelcacheonk8s
    depends_on:
      - consul-client

  auth:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - multilevelcacheonk8s
    depends_on:
      - consul-client

networks:
  multilevelcacheonk8s:
    external:
      name: multilevelcacheonk8s
