version: '3.4'

services:
  apigateway:
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: gateway/apigateway/Dockerfile

  sample-a:
    image: ${DOCKER_REGISTRY-}samplea
    build:
      context: .
      dockerfile: services/a/sample_a/Dockerfile

  sample-b:
    image: ${DOCKER_REGISTRY-}sampleb
    build:
      context: .
      dockerfile: services/b/sample_b/Dockerfile

  auth:
    image: ${DOCKER_REGISTRY-}auth
    build:
      context: .
      dockerfile: sso/auth/Dockerfile

